# Generated by Django 4.0.5 on 2022-07-01 06:44

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('mobile', models.CharField(db_index=True, max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('pin_code', models.CharField(db_index=True, max_length=10)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('otp_var', models.CharField(default='', max_length=10)),
                ('is_varified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('place_name', models.CharField(db_index=True, max_length=200)),
                ('state_name', models.CharField(db_index=True, max_length=100)),
                ('postal_code', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user_id', 'state_name', 'postal_code'], fillfactor=30, name='auth_servic_user_id_df7bd3_btree'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['full_name', 'pin_code', 'id'], fillfactor=40, name='auth_servic_full_na_4efb0d_btree'),
        ),
    ]
