# Generated by Django 4.0.5 on 2022-07-13 19:12

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='auth_servic_full_na_4efb0d_btree',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, default='6d47e5', max_length=100),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['full_name', 'pin_code', 'id', 'user_id'], fillfactor=40, name='auth_servic_full_na_cfa619_btree'),
        ),
    ]
