# Generated by Django 4.0.5 on 2022-07-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_remove_user_auth_servic_full_na_4efb0d_btree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, default='5810f6f', max_length=100),
        ),
    ]
