# Generated by Django 4.0.5 on 2022-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, default='ef31a8c', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='place_name',
            field=models.CharField(db_index=True, max_length=600),
        ),
    ]
