# Generated by Django 4.0.5 on 2022-07-24 15:32

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_alter_user_user_id_alter_useraddress_place_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useraddress',
            name='auth_servic_user_id_df7bd3_btree',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, default='2e60337', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user_id', 'state_name', 'postal_code'], fillfactor=30, name='auth_servic_user_id_b88360_btree'),
        ),
    ]
