# Generated by Django 4.0.5 on 2022-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followersapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='following_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
    ]
