# Generated by Django 4.0.5 on 2022-07-13 20:26

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followersapi', '0002_alter_followers_following_id_alter_followers_user_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followers',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user_id', 'following_id', 'id'], fillfactor=30, name='followersap_user_id_62ca1e_btree'),
        ),
    ]
